CREATE TABLE MEMBER (
	MNUM INT PRIMARY KEY,
	MID VARCHAR(15),
	MPW VARCHAR(15)
);

DROP TABLE MEMBER;

SELECT * FROM MEMBER;

INSERT INTO MEMBER VALUES (1, 'young', '1234');
INSERT INTO MEMBER VALUES (2, 'jin', '1234');

SELECT * FROM MEMBER;
delete member where mnum=3;